name: Scan Audit

on:
  workflow_dispatch:
    inputs:
      dev:
        description: Audit the dev environment [true/false]
        default: false
        required: true
      test:
        description: Audit the test environment [true/false]
        default: false
        required: true

# on:
#   repository_dispatch:
#     types: scan-audit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output
        # env:
        #   dev: true
        #   test: false
        run: |
        
          echo " the dev input =  ${{ github.event.inputs.dev}}"
          echo " the test input = ${{ github.event.inputs.test}}"

          echo " the dev input =  ${{ github.event.client_payload}}"
          echo " the dev input =  ${{ github.event.client_payload.dev}}"
          echo " the test input = ${{ github.event.client_payload.test}}"

          # echo " the  dev env should be  ${dev}"
          # echo " the test env should be ${test}"
        
        - name: Check the Dev Environment
          if: github.event.inputs.dev === 'true'
          run: |
            az vm show -g dev -n dev-web-az1  && 
            az vm show -g dev -n dev-master-az1 


# # on:
# #   workflow_dispatch:
# #     inputs:
# #       dev:
# #         description: Audit the dev environment [true/false]
# #         default: false
# #         required: true
# #       test:
# #         description: Audit the test environment [true/false]
# #         default: false
# #         required: true

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: "Output the variables"
#         env:
#           dev: ${{ github.event.client_payload.dev }}
#           # test: ${{ github.event.client_payload.test }}
#         run: |
#             echo "just print some output ${{ dev }}"